// flow-typed signature: 1e194bd1d5aa841d7f073ad18202e52f
// flow-typed version: <<STUB>>/electron_v3.0.6/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron/cli' {
  declare module.exports: any;
}

declare module 'electron/install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron/cli.js' {
  declare module.exports: $Exports<'electron/cli'>;
}
declare module 'electron/index' {
  declare module.exports: $Exports<'electron'>;
}
declare module 'electron/index.js' {
  declare module.exports: $Exports<'electron'>;
}
declare module 'electron/install.js' {
  declare module.exports: $Exports<'electron/install'>;
}
