// flow-typed signature: a3f02b2a6169191059a314d45970b1d9
// flow-typed version: <<STUB>>/fluent-ffmpeg_v2.1.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fluent-ffmpeg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fluent-ffmpeg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fluent-ffmpeg/doc/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/doc/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/doc/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/capabilities' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/ffprobe' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/fluent-ffmpeg' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/options/audio' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/options/custom' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/options/inputs' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/options/misc' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/options/output' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/options/video' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/options/videosize' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/presets/divx' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/presets/flashvideo' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/presets/podcast' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/processor' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/recipes' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/lib/utils' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/tools/jsdoc-aliases' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/tools/jsdoc-template/publish' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/tools/jsdoc-template/static/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/tools/jsdoc-template/static/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'fluent-ffmpeg/tools/jsdoc-template/static/scripts/prettify/prettify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fluent-ffmpeg/doc/scripts/linenumber.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/doc/scripts/linenumber'>;
}
declare module 'fluent-ffmpeg/doc/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/doc/scripts/prettify/lang-css'>;
}
declare module 'fluent-ffmpeg/doc/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/doc/scripts/prettify/prettify'>;
}
declare module 'fluent-ffmpeg/index' {
  declare module.exports: $Exports<'fluent-ffmpeg'>;
}
declare module 'fluent-ffmpeg/index.js' {
  declare module.exports: $Exports<'fluent-ffmpeg'>;
}
declare module 'fluent-ffmpeg/lib/capabilities.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/capabilities'>;
}
declare module 'fluent-ffmpeg/lib/ffprobe.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/ffprobe'>;
}
declare module 'fluent-ffmpeg/lib/fluent-ffmpeg.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/fluent-ffmpeg'>;
}
declare module 'fluent-ffmpeg/lib/options/audio.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/options/audio'>;
}
declare module 'fluent-ffmpeg/lib/options/custom.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/options/custom'>;
}
declare module 'fluent-ffmpeg/lib/options/inputs.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/options/inputs'>;
}
declare module 'fluent-ffmpeg/lib/options/misc.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/options/misc'>;
}
declare module 'fluent-ffmpeg/lib/options/output.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/options/output'>;
}
declare module 'fluent-ffmpeg/lib/options/video.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/options/video'>;
}
declare module 'fluent-ffmpeg/lib/options/videosize.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/options/videosize'>;
}
declare module 'fluent-ffmpeg/lib/presets/divx.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/presets/divx'>;
}
declare module 'fluent-ffmpeg/lib/presets/flashvideo.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/presets/flashvideo'>;
}
declare module 'fluent-ffmpeg/lib/presets/podcast.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/presets/podcast'>;
}
declare module 'fluent-ffmpeg/lib/processor.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/processor'>;
}
declare module 'fluent-ffmpeg/lib/recipes.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/recipes'>;
}
declare module 'fluent-ffmpeg/lib/utils.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/lib/utils'>;
}
declare module 'fluent-ffmpeg/tools/jsdoc-aliases.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/tools/jsdoc-aliases'>;
}
declare module 'fluent-ffmpeg/tools/jsdoc-template/publish.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/tools/jsdoc-template/publish'>;
}
declare module 'fluent-ffmpeg/tools/jsdoc-template/static/scripts/linenumber.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/tools/jsdoc-template/static/scripts/linenumber'>;
}
declare module 'fluent-ffmpeg/tools/jsdoc-template/static/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/tools/jsdoc-template/static/scripts/prettify/lang-css'>;
}
declare module 'fluent-ffmpeg/tools/jsdoc-template/static/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'fluent-ffmpeg/tools/jsdoc-template/static/scripts/prettify/prettify'>;
}
