// flow-typed signature: 18eb29648e6c6c91e2c2b1cfa67404b5
// flow-typed version: <<STUB>>/subsrt_v1.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'subsrt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'subsrt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'subsrt/app' {
  declare module.exports: any;
}

declare module 'subsrt/bin/subsrt' {
  declare module.exports: any;
}

declare module 'subsrt/lib/format/ass' {
  declare module.exports: any;
}

declare module 'subsrt/lib/format/json' {
  declare module.exports: any;
}

declare module 'subsrt/lib/format/lrc' {
  declare module.exports: any;
}

declare module 'subsrt/lib/format/sbv' {
  declare module.exports: any;
}

declare module 'subsrt/lib/format/smi' {
  declare module.exports: any;
}

declare module 'subsrt/lib/format/srt' {
  declare module.exports: any;
}

declare module 'subsrt/lib/format/ssa' {
  declare module.exports: any;
}

declare module 'subsrt/lib/format/sub' {
  declare module.exports: any;
}

declare module 'subsrt/lib/format/vtt' {
  declare module.exports: any;
}

declare module 'subsrt/lib/subsrt' {
  declare module.exports: any;
}

declare module 'subsrt/test/build' {
  declare module.exports: any;
}

declare module 'subsrt/test/convert' {
  declare module.exports: any;
}

declare module 'subsrt/test/detect' {
  declare module.exports: any;
}

declare module 'subsrt/test/parse' {
  declare module.exports: any;
}

declare module 'subsrt/test/resync' {
  declare module.exports: any;
}

declare module 'subsrt/test/time' {
  declare module.exports: any;
}

// Filename aliases
declare module 'subsrt/app.js' {
  declare module.exports: $Exports<'subsrt/app'>;
}
declare module 'subsrt/bin/subsrt.js' {
  declare module.exports: $Exports<'subsrt/bin/subsrt'>;
}
declare module 'subsrt/lib/format/ass.js' {
  declare module.exports: $Exports<'subsrt/lib/format/ass'>;
}
declare module 'subsrt/lib/format/json.js' {
  declare module.exports: $Exports<'subsrt/lib/format/json'>;
}
declare module 'subsrt/lib/format/lrc.js' {
  declare module.exports: $Exports<'subsrt/lib/format/lrc'>;
}
declare module 'subsrt/lib/format/sbv.js' {
  declare module.exports: $Exports<'subsrt/lib/format/sbv'>;
}
declare module 'subsrt/lib/format/smi.js' {
  declare module.exports: $Exports<'subsrt/lib/format/smi'>;
}
declare module 'subsrt/lib/format/srt.js' {
  declare module.exports: $Exports<'subsrt/lib/format/srt'>;
}
declare module 'subsrt/lib/format/ssa.js' {
  declare module.exports: $Exports<'subsrt/lib/format/ssa'>;
}
declare module 'subsrt/lib/format/sub.js' {
  declare module.exports: $Exports<'subsrt/lib/format/sub'>;
}
declare module 'subsrt/lib/format/vtt.js' {
  declare module.exports: $Exports<'subsrt/lib/format/vtt'>;
}
declare module 'subsrt/lib/subsrt.js' {
  declare module.exports: $Exports<'subsrt/lib/subsrt'>;
}
declare module 'subsrt/test/build.js' {
  declare module.exports: $Exports<'subsrt/test/build'>;
}
declare module 'subsrt/test/convert.js' {
  declare module.exports: $Exports<'subsrt/test/convert'>;
}
declare module 'subsrt/test/detect.js' {
  declare module.exports: $Exports<'subsrt/test/detect'>;
}
declare module 'subsrt/test/parse.js' {
  declare module.exports: $Exports<'subsrt/test/parse'>;
}
declare module 'subsrt/test/resync.js' {
  declare module.exports: $Exports<'subsrt/test/resync'>;
}
declare module 'subsrt/test/time.js' {
  declare module.exports: $Exports<'subsrt/test/time'>;
}
