// flow-typed signature: 753f9341a41787997be091884479ce80
// flow-typed version: <<STUB>>/subtitle_v2.0.3/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'subtitle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'subtitle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'subtitle/dist/subtitle.bundle' {
  declare module.exports: any;
}

declare module 'subtitle/lib/index' {
  declare module.exports: any;
}

declare module 'subtitle/lib/parse' {
  declare module.exports: any;
}

declare module 'subtitle/lib/parseTimestamps' {
  declare module.exports: any;
}

declare module 'subtitle/lib/resync' {
  declare module.exports: any;
}

declare module 'subtitle/lib/stringify' {
  declare module.exports: any;
}

declare module 'subtitle/lib/stringifyVtt' {
  declare module.exports: any;
}

declare module 'subtitle/lib/toMS' {
  declare module.exports: any;
}

declare module 'subtitle/lib/toSrtTime' {
  declare module.exports: any;
}

declare module 'subtitle/lib/toVttTime' {
  declare module.exports: any;
}

declare module 'subtitle/test/parse.test' {
  declare module.exports: any;
}

declare module 'subtitle/test/parseTimestamps.test' {
  declare module.exports: any;
}

declare module 'subtitle/test/resync.test' {
  declare module.exports: any;
}

declare module 'subtitle/test/stringify.test' {
  declare module.exports: any;
}

declare module 'subtitle/test/stringifyVtt.test' {
  declare module.exports: any;
}

declare module 'subtitle/test/toMS.test' {
  declare module.exports: any;
}

declare module 'subtitle/test/toSrtTime.test' {
  declare module.exports: any;
}

declare module 'subtitle/test/toVttTime.test' {
  declare module.exports: any;
}

declare module 'subtitle/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'subtitle/dist/subtitle.bundle.js' {
  declare module.exports: $Exports<'subtitle/dist/subtitle.bundle'>;
}
declare module 'subtitle/lib/index.js' {
  declare module.exports: $Exports<'subtitle/lib/index'>;
}
declare module 'subtitle/lib/parse.js' {
  declare module.exports: $Exports<'subtitle/lib/parse'>;
}
declare module 'subtitle/lib/parseTimestamps.js' {
  declare module.exports: $Exports<'subtitle/lib/parseTimestamps'>;
}
declare module 'subtitle/lib/resync.js' {
  declare module.exports: $Exports<'subtitle/lib/resync'>;
}
declare module 'subtitle/lib/stringify.js' {
  declare module.exports: $Exports<'subtitle/lib/stringify'>;
}
declare module 'subtitle/lib/stringifyVtt.js' {
  declare module.exports: $Exports<'subtitle/lib/stringifyVtt'>;
}
declare module 'subtitle/lib/toMS.js' {
  declare module.exports: $Exports<'subtitle/lib/toMS'>;
}
declare module 'subtitle/lib/toSrtTime.js' {
  declare module.exports: $Exports<'subtitle/lib/toSrtTime'>;
}
declare module 'subtitle/lib/toVttTime.js' {
  declare module.exports: $Exports<'subtitle/lib/toVttTime'>;
}
declare module 'subtitle/test/parse.test.js' {
  declare module.exports: $Exports<'subtitle/test/parse.test'>;
}
declare module 'subtitle/test/parseTimestamps.test.js' {
  declare module.exports: $Exports<'subtitle/test/parseTimestamps.test'>;
}
declare module 'subtitle/test/resync.test.js' {
  declare module.exports: $Exports<'subtitle/test/resync.test'>;
}
declare module 'subtitle/test/stringify.test.js' {
  declare module.exports: $Exports<'subtitle/test/stringify.test'>;
}
declare module 'subtitle/test/stringifyVtt.test.js' {
  declare module.exports: $Exports<'subtitle/test/stringifyVtt.test'>;
}
declare module 'subtitle/test/toMS.test.js' {
  declare module.exports: $Exports<'subtitle/test/toMS.test'>;
}
declare module 'subtitle/test/toSrtTime.test.js' {
  declare module.exports: $Exports<'subtitle/test/toSrtTime.test'>;
}
declare module 'subtitle/test/toVttTime.test.js' {
  declare module.exports: $Exports<'subtitle/test/toVttTime.test'>;
}
declare module 'subtitle/webpack.config.js' {
  declare module.exports: $Exports<'subtitle/webpack.config'>;
}
