name: MacOS Node CI

on:
  push:
    paths-ignore:
      - 'homepage/**'

jobs:
  mac_build:
    runs-on: macos-13

    strategy:
      matrix:
        node-version: [20.17.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: test env
        env:
          RELEASE_BUILD: ${{startsWith(github.ref, 'refs/tags/')}}
          NON_RELEASE_BUILD: ${{!startsWith(github.ref, 'refs/tags/')}}
        run: |
          node -e "console.log(process.env.RELEASE_BUILD, typeof process.env.RELEASE_BUILD)"
          node -e "console.log(process.env.NON_RELEASE_BUILD, typeof process.env.NON_RELEASE_BUILD)"
      - name: Cache npm dependencies
        id: cache-npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
            ${{ runner.os }}-node-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: npm install and test
        run: |
          npm ci
          npm run format -- --list-different
          npm run lint
          npm run tsc
          npm run test
      - name: integration tests
        run: |
          npm run integration
      - name: build
        run: npm run dist -- --mac
        env:
          CI: true
          # one for electron builder, one for vite
          BUILD_NUMBER: ${{ github.run_number }}_${{ github.run_id }}_${{ github.run_attempt }}
          VITE_BUILD_NUMBER: ${{ github.run_number }}_${{ github.run_id }}_${{ github.run_attempt }}
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload test screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: screenshots
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: logs
      - name: Upload build artifacts
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/Knowclip_*
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: dist/Knowclip_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
