name: MacOS Node CI

on:
  push:
    paths-ignore:
      - 'homepage/**'

jobs:
  mac_build:
    runs-on: macos-13

    strategy:
      matrix:
        node-version: [20.17.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm ci
          npm run format -- --list-different
          npm run lint
          npm run tsc
          npm run test
      - name: integration tests
        run: |
          npm run integration
      - name: build
        run: npm run dist -- --mac
        env:
          CI: true
          BUILD_NUMBER: ${{ github.run_number }}_${{ github.run_id }}_${{ github.run_attempt }}
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload test screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: screenshots
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: '*.log'
          path: logs
      - name: Upload build artifacts
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/Knowclip_*
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: dist/Knowclip_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
