name: Windows Node CI

on:
  push:
      paths-ignore:
      - 'homepage/**'

jobs:
  win_build_and_test:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: integration test
      run: |
        npm ci
        npm run integration:win -- -t "shared project"
      env:
        REACT_APP_CHROMEDRIVER: true
        SPECTRON_LOG_FAILURES: true
        APPVEYOR: true
    - name: Upload test screenshots
      uses: actions/upload-artifact@v2
      with:
        name: tmp-test
        path: tmp-test
    - name: build
      run: |
        npm run dist:appveyor -- --win
      env:
        APPVEYOR: true
        CI: false
    - name: Upload test screenshots
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-screenshots
        path: screenshots
    - name: Upload build artifacts
      if: "!startsWith(github.ref, 'refs/tags/')"
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/Knowclip_*
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: dist/Knowclip_*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



